// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System;
using System.IO;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using UnityEngine;

using static Microsoft.MixedReality.Toolkit.Extensions.SharingServiceProfile;

namespace Microsoft.MixedReality.Toolkit.Extensions.Sharing.Communication
{
    public static class SharingServiceResources
    {
        /// <summary>
        /// The prefix used for generated prefabs variants.
        /// </summary>
        public static string GeneratedPrefix = "_Generated_";

        /// <summary>
        /// Convert a resource to a version that will work for the given sharing provider.
        /// </summary>
        public static async Task<GameObject> Convert(ProviderService service, GameObject original)
        {
            if (original == null)
            {
                return null;
            }

            string name = Convert(service, original.name);
            var result = await Resources.LoadAsync(name).AsTask<GameObject>();

            if (result == null)
            {
                result = original;
            }

            return result;
        }

        /// <summary>
        /// Convert a resource name to a name that will work for the given sharing provider.
        /// </summary>
        public static string Convert(ProviderService service, string name)
        {
            return $"{GeneratedPrefix}{service}_{name}";
        }

        /// <summary>
        /// Determine if the given resource used generated by this service component.
        /// </summary>
        public static bool IsGenerated(GameObject gameObject)
        {
            return gameObject != null && IsGenerated(gameObject.name);
        }

        /// <summary>
        /// Determine if the given resource used generated by this service component.
        /// </summary>
        public static bool IsGenerated(string name)
        {
            return !string.IsNullOrEmpty(name) && name.StartsWith(GeneratedPrefix);
        }
    }

#if UNITY_EDITOR
    public class SharingServiceResourceEditorRunner : UnityEditor.Build.IPreprocessBuildWithReport
    {
        public int callbackOrder { get { return 0; } }

        [RuntimeInitializeOnLoadMethod]
        private static void CreateVariants()
        {
#if PHOTON_INSTALLED
            (new Photon.PhotonResourceEditor()).CreateVariants();
#endif
        }

        /// <summary>
        /// Prepare sharing service variants of sharable prefab resources.
        /// </summary>
        public void OnPreprocessBuild(UnityEditor.Build.Reporting.BuildReport report)
        {
            CreateVariants();
        }
    }

    public class SharingServiceResourceEditor 
    {
        private ProviderService _service;

        protected SharingServiceResourceEditor(ProviderService service)
        {
            _service = service;
        }

        /// <summary>
        /// Get the resource folder
        /// </summary>
        public string ResourceFolder => $"{_service}\\Generated\\Resources";

        /// <summary>
        /// Prepare sharing service variants of sharable prefab resources.
        /// </summary>
        public void CreateVariants()
        { 
            var prefabs = Resources.LoadAll<GameObject>(string.Empty);
            foreach (var prefab in prefabs)
            {               
                if (!SharingServiceResources.IsGenerated(prefab) &&
                    prefab.GetComponent<SharingObject>() != null)
                {
                    Create(prefab);
                }
            }
        }

        /// <summary>
        /// Copy an original resource and create a version that is supported by the Sharing Service provider.
        /// </summary>
        /// <param name="original"></param>
        private void Create(GameObject original)
        {
            var resourcesDirectory = GetFolder();
            var name = SharingServiceResources.Convert(_service, original.name);
            var filePath = $"{resourcesDirectory.FullName}\\{name}.prefab";
            var resourcesPath = resourcesDirectory.FullName.Replace(Application.dataPath, "Assets");

            if (!File.Exists(filePath))
            {
                GameObject instanceRoot = UnityEditor.PrefabUtility.InstantiatePrefab(original) as GameObject;
                InitializeVariant(instanceRoot);

                UnityEditor.PrefabUtility.SaveAsPrefabAsset(instanceRoot, $"{resourcesPath}\\{name}.prefab");
                UnityEngine.Object.DestroyImmediate(instanceRoot);
            }
        }

        protected virtual void InitializeVariant(GameObject variant)
        {
        }

        private DirectoryInfo GetFolder([CallerFilePath] string filePath = "")
        {
            string path = $"{Path.GetDirectoryName(filePath)}\\{ResourceFolder}";
            DirectoryInfo directory = new DirectoryInfo(path);

            if (!directory.Exists)
            {
                directory.Create();
            }

            return directory;
        }
    }
#endif 
}
